server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://{{ loki_ip }}:3100/loki/api/v1/push

scrape_configs:
- job_name: system
  static_configs:
  - labels:
      host: {{ host_name }}
      __path__: /var/log/{messages,secure,cmd.log}
